### ISSUE TITLE
Deprecating `rsa-fdh` in favour of this crate

### ISSUE THREAD

**Issue by phayes** [jedisct1/rust-blind-rsa-signatures#1]
Hi there, 

I'm the author of [rsa-fdh](https://github.com/phayes/rsa-fdh).  I've reviewed the code in `rust-blind-rsa-signatures`, and really appreciate how well it's written and it's adherance to the IETF Standard.   

How would you feel about my deprecating the `rsa-fdh` crate and recommending this crate as it's successor?

**Comment by jedisct1** [comment]
Hi! And sorry for the delayed response! Just realized that notifications were not enabled for this repository 🤦

As you probably noticed, we recently added support for empty salts to the draft, which effectively turns the padding scheme to FDH.

This crate implements both, and, along with the Zig and C implementations, will keep being updated along with changes to the specification. So it indeed may be a bit redundant with `rsa-fdh`, and if you feel like recommending this one in order to avoid duplicate efforts, go for it!

Contributions are also more than welcome!

Cheers!
